---
title: Mapping data
hero_image: images/banner.png
description:
  Use Python to make an interactive map that lets users learn interesting
  facts about the world
meta_title: Python coding projects for kids and teens | Mapping data
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to make a map and learn interesting facts about the world.
version: 4
listed: false
copyedit: false
last_tested: "2026-01-12"
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
  completion:
  - internal
  - external